name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18, 11 & 8
      uses: actions/setup-java@v3
      with:
        java-version: |
          18
          11
          8
        distribution: 'temurin'
    - name: Build with Gradle for Java 8
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
    - name: Patch Gradle Settings for Java 11 Build
      run: |
        sed -i 's/^java.version=[0-9]+$/java.version=11/g' gradle.properties
    - name: Build with Gradle for Java 11
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
    - name: Patch Gradle Settings for Java 18 Build
      run: |
        sed -i 's/^java.version=[0-9]+$/java.version=18/g' gradle.properties
    - name: Build with Gradle for Java 18
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
    - uses: actions/upload-artifact@v3
      with:
        name: GameProject
        path: build/libs/GameProject*.jar